In [1]:
x= 5

In [2]:
x

In [3]:
type(x)

In [4]:
a="hello"
a

'hello'

In [5]:
a =["a","b","c"]
a

['a', 'b', 'c']

In [6]:
a.append("d")
a

['a', 'b', 'c', 'd']

In [7]:
a.insert(1,2)
a

['a', 2, 'b', 'c', 'd']

In [8]:
a.pop()
a

['a', 2, 'b', 'c']

In [9]:
a.remove("c")
a

['a', 2, 'b']

In [10]:
a.remove(2)

In [11]:
a.sort()

In [12]:
a

['a', 'b']

In [13]:
d ={
    'a1':24,
    'a2':36
}
d

{'a1': 24, 'a2': 36}

In [14]:
x=list(range(5))

x

[0, 1, 2, 3, 4]

In [13]:
x=list(range(5))
print(x)
for y in x:
    y=y+2
    print(y)

[0, 1, 2, 3, 4]
2
3
4
5
6


In [2]:
n = [9,8,7,6,5]
n.append(4)
print(n)



[9, 8, 7, 6, 5, 4]


In [17]:
n = [9,8,7,6,5]
n.append(4)
print(n)
n.insert(2,11)
print(n)
print(len(n))


[9, 8, 7, 6, 5, 4]
[9, 8, 11, 7, 6, 5, 4]
7


In [ ]:
for x in range(1,10):
    x=x**2
    print(x)

In [ ]:
for x in range(1,10):
    x=x%2==0
    print(x)

In [3]:
map(lambda x: x + 10, range(10))


# numpy

In [18]:
import numpy as np


In [6]:
x1= np.random.randint(10,size=(6)) #1d array #only colmn
x1

array([9, 8, 4, 7, 6, 8])

In [7]:
x1= np.random.randint(10,size=(6,1)) #1d array #only row
x1

array([[1],
       [5],
       [9],
       [0],
       [8],
       [6]])

In [8]:
x2= np.random.randint(20, size=(4,5)) #2d array
x2

array([[ 7,  7,  2,  7,  5],
       [17, 14, 12, 19,  3],
       [ 8,  8,  0,  7, 10],
       [ 2, 14,  6,  8,  0]])

In [16]:
x3= np.random.randint(30,size=(6,5,3)) #3d array
x3

array([[[ 5, 11,  0],
        [28,  6,  7],
        [18, 18,  9],
        [29, 22, 24],
        [17, 29,  5]],

       [[ 8, 17, 10],
        [ 8, 12, 28],
        [27, 18,  1],
        [24, 11, 13],
        [27,  4, 29]],

       [[ 3, 23, 14],
        [22,  0, 16],
        [ 0, 25, 14],
        [25, 14,  6],
        [24, 23, 12]],

       [[ 1,  2,  8],
        [14, 27, 17],
        [ 4, 25, 28],
        [ 2,  6, 28],
        [14,  3, 15]],

       [[11, 18,  4],
        [17, 22,  5],
        [10, 22, 24],
        [ 8, 19, 29],
        [24, 17, 13]],

       [[16, 14, 10],
        [15,  0,  4],
        [17, 26, 20],
        [15, 25, 23],
        [10, 15,  6]]])

In [17]:
x3[4,1,2]

5

In [ ]:
print(x3.ndim) #dimension
print(x3.shape) #shape
print(x3.size) #size

In [ ]:
name= input("enter your name")

In [ ]:
name

In [ ]:
marks= float(input("Enter marks: "))

In [ ]:
marks


# game 

In [3]:
for i in range(3):
    value = np.random.randint(1,4)

    number = int(input("Enter a integer number"))

    if number == value:
       print("You chose", number )
       print("random_number : ", value )
       print("You win!")
    else:
        print("You chose", number )
        print("random_number : ", value )
        print("You loose")
    

Enter a integer number5
You chose 5
random_number :  2
You loose
Enter a integer number2
You chose 2
random_number :  3
You loose


KeyboardInterrupt: Interrupted by user

In [ ]:
num = np.random.randint(1,4)
print("Guess a number between 1 and 4 numbers \nYou have 2 chances ")
for i in range(2):
    guess = int(input("Enter Your Guess: "))
    if guess == num :
        print("right")
    else :
        print("Try again...")
print("\nFinished")


In [ ]:
import random
num = random.randint(1,13)
print("Guess a number between 1 and 13 integer number \nYou have 2 chances ")
for i in range(2):
    guess = int(input("Enter Your Guess: "))
    if guess == num :
        print("Congrats! You did it")
    else :
        print("Try again...")
print("\nFinished")


In [ ]:
#aniket47kr@gmail.com


In [ ]:
#day 9 

In [ ]:
#write a program to print the count of the numbers
numb=int(input("enter nmbers:"))
count=0
for num in numb: 
    count=count+1
print(count)

In [4]:
n=input("enter anything :")
count=0
for num in n: 
    count=count+1
print(count)

enter numbers:abbasl223
9


In [12]:
n = int(input("enter the number: "))
limit = 100
for num in range(n, limit+1): 
    if num > 1:
        for i in range(2, num): 
            if (num % i) == 0:
                print(num,"not a prime")
                break 
        else:
           print(num,"prime")


enter the number: 1
2 prime
3 prime
4 not a prime
5 prime
6 not a prime
7 prime
8 not a prime
9 not a prime
10 not a prime
11 prime
12 not a prime
13 prime
14 not a prime
15 not a prime
16 not a prime
17 prime
18 not a prime
19 prime
20 not a prime
21 not a prime
22 not a prime
23 prime
24 not a prime
25 not a prime
26 not a prime
27 not a prime
28 not a prime
29 prime
30 not a prime
31 prime
32 not a prime
33 not a prime
34 not a prime
35 not a prime
36 not a prime
37 prime
38 not a prime
39 not a prime
40 not a prime
41 prime
42 not a prime
43 prime
44 not a prime
45 not a prime
46 not a prime
47 prime
48 not a prime
49 not a prime
50 not a prime
51 not a prime
52 not a prime
53 prime
54 not a prime
55 not a prime
56 not a prime
57 not a prime
58 not a prime
59 prime
60 not a prime
61 prime
62 not a prime
63 not a prime
64 not a prime
65 not a prime
66 not a prime
67 prime
68 not a prime
69 not a prime
70 not a prime
71 prime
72 not a prime
73 prime
74 not a prime
75 not a prime
76 n

In [ ]:
#numpy day 10 

In [12]:
nmp=np.array(['5','6'])
nmp

array(['5', '6'], dtype='<U1')

In [18]:
x3= np.random.randint(30,size=(6,5,3)) #3d array
x3

array([[[ 1, 23,  7],
        [16, 10, 27],
        [20, 10,  4],
        [11, 24, 18],
        [ 8, 20,  7]],

       [[ 0, 16,  7],
        [ 0, 21, 28],
        [ 0, 29, 24],
        [ 0, 22, 22],
        [13, 27, 19]],

       [[16,  4, 10],
        [23, 17, 12],
        [25, 15, 28],
        [17, 18, 14],
        [21, 18,  0]],

       [[23, 15,  8],
        [29, 28, 18],
        [18, 22,  1],
        [ 9,  6,  5],
        [27, 19, 16]],

       [[11, 26, 23],
        [20, 14,  4],
        [22, 14, 18],
        [ 6, 27, 18],
        [ 9, 25,  3]],

       [[11, 11,  0],
        [ 4, 15, 26],
        [13,  7, 20],
        [28, 23, 25],
        [28,  3, 13]]])

In [20]:
x3[4,2,0]

22

In [25]:
x6= np.random.randint(10,size=(6))
x6

array([1, 8, 9, 1, 2, 6])

## slicing

In [26]:
x6[:5]

array([1, 8, 9, 1, 2])

In [28]:
x6[0:3]

array([1, 8, 9])

In [29]:
x6[4:]

array([2, 6])

In [30]:
x6[::2] #gives result from 0th position to end with the increment of 2

array([1, 9, 2])

In [32]:
x6[::-1] #reverse the array

array([6, 2, 1, 9, 8, 1])

In [34]:
x6[3::-1]

array([1, 9, 8, 1])

In [37]:
x2= np.random.randint(20, size=(3,3)) #2d array
x2

array([[ 5,  9,  7],
       [13, 18,  5],
       [10,  6, 13]])

In [38]:
x2[:2,:] #sets limit like first 2 row will show 3rd will not

array([[ 5,  9,  7],
       [13, 18,  5]])

In [39]:
x2[::2,::2]

array([[ 5,  7],
       [10, 13]])

In [40]:
x2[::-1,::-1] #transpose manner or reverse 

array([[13,  6, 10],
       [ 5, 18, 13],
       [ 7,  9,  5]])

In [44]:
x2[0,:]=2.222 #only int value added , the float value will be truncated
x2

array([[ 2,  2,  2],
       [13, 18,  5],
       [10,  6, 13]])

## concatenate

In [46]:
n1= np.array([1,2,3])
n2=np.array([4,5,6])
np.concatenate([n1,n2])

array([1, 2, 3, 4, 5, 6])

In [48]:
grid= np.array([[1,2,3],
              [4,5,6]])

In [49]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [50]:
x=[1,2,3,6,79,79,90,9]
x1,x2,x3= np.split(x,(1,5)) #splitting into 3 array
x1,x2,x3

(array([1]), array([ 2,  3,  6, 79]), array([79, 90,  9]))

# table

6


TypeError: 'num' is an invalid keyword argument for print()

In [31]:
#sum of count of input

a=int(input("enter the number\n"))
def sum(x):
    if(x<1):
        return 0
    return x%10+sum(x//10)
print(sum(a))

enter the number
566
17


In [33]:
s1 = input()
s2 = input()

new_s1 = s1.split()
#print(set(new_s1))
#print(new_s1)
new_s2 = s2.split()
set(new_s2)
comm_words = set(new_s1) & set(new_s2)
print((comm_words))

hi
hi
1


# Pandas

In [1]:
import pandas as pd

In [ ]:
#Q1 difference between numpy array and pandas series data

In [4]:
x1= pd.Series([1,2,3,4]) #series "S" always be cap
x1 

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
x2= pd.Series([1,2,3,4],index=["a","b","c","d"])
x2

a    1
b    2
c    3
d    4
dtype: int64

In [15]:
a={'key1':12, 'key2':13, 'key1':14} #if same key's exist with different values it takes values from back
a

{'key1': 14, 'key2': 13}

In [16]:
#what if we have 3 values and 4 indexes in series, it gives error .(length of passed value is 3, index implies 4) 
a=pd.Series([1,2,3], index=["A","B","C","D"])  
a 

ValueError: Length of passed values is 3, index implies 4.

In [19]:
x= np.array(["a","b","c","c"])
p=pd.Series(x) #if we have similar indexes , it doesnot bother it stores the value
p

0    a
1    b
2    c
3    c
dtype: object

In [23]:
c1= pd.Series(7,index=["a","b","c","d","e","g","g"])
c1

a    7
b    7
c    7
d    7
e    7
g    7
g    7
dtype: int64

In [26]:
c1[5] #extracting a single element

7

In [27]:
c1["g"]

g    7
g    7
dtype: int64

In [28]:
c1[::3] #increment +3

a    7
d    7
g    7
dtype: int64

# Retrieve data using Label(index)

# day 12

In [1]:
import numpy as np
import pandas as pd 

In [2]:
a= pd.Series(np.random.randn(50).round(2)) #float values using numpy
a

0     1.61
1     0.51
2     0.87
3     1.11
4     0.70
5     0.54
6    -0.09
7    -0.05
8    -0.85
9    -1.72
10   -0.62
11   -2.07
12   -1.52
13    0.16
14   -0.54
15    0.80
16   -0.79
17   -1.89
18   -0.32
19    0.50
20    0.58
21   -0.33
22    0.05
23   -0.21
24   -1.08
25    0.39
26   -1.12
27   -0.46
28   -1.06
29    0.29
30   -0.02
31    1.24
32   -0.18
33   -0.29
34   -0.50
35    0.06
36   -0.87
37   -0.45
38   -0.94
39    0.57
40   -0.21
41   -1.95
42   -1.38
43    1.05
44    0.82
45    0.35
46    0.92
47   -0.62
48    1.30
49    0.53
dtype: float64

In [3]:
a.head(n=10) #first 10

0    1.61
1    0.51
2    0.87
3    1.11
4    0.70
5    0.54
6   -0.09
7   -0.05
8   -0.85
9   -1.72
dtype: float64

In [4]:
a.tail(n=10) #last 10

40   -0.21
41   -1.95
42   -1.38
43    1.05
44    0.82
45    0.35
46    0.92
47   -0.62
48    1.30
49    0.53
dtype: float64

In [ ]:
#perfect number

In [5]:
num = int(input())

f=list()

for i in range(1,num):
    if num%i ==0:
        f.append(i)

print(sum(f) == num)

6
True


In [6]:
def pf(x):
    temp = 0
    for i in range(1,x):
        if(x%i==0):
            temp+=i
    if (temp==x):
        print(str(x)+" is perfect number")
    else:
        print(str(x)+" is not perfect number")
x = int(input("Enter your number to check: "))
pf(x)


Enter your number to check: 6
6 is perfect number


In [11]:
n = int(input("Insert a number: ")) #n= 6 
sum = 0
for i in range(1, n): 
    if n % i == 0: #6%1,6%2 , 6%3 
        sum += i #1,#3, #6
if sum == n:
    print(str(n) + " is a perfect number")
else:
    print(str(n) + " is NOT a perfect number")
    

#input value tak loop chalega or unki jo value hogi wo first divisible condition m jayega like if it is divisible by the loop numbers then it will goes to next condition where it added into new variable (which contains only those values which are divisible by the loop numbers(like 6 is divisible by 1,2,3(where 1,2,3 are loop numbers)) then it will check if the input or sum values are same then it's a perfect number otherwise not.) )

Insert a number: 28
28 is a perfect number


# outliers

In [12]:
a.astype(str).head #convert data into string

<bound method NDFrame.head of 0      1.61
1      0.51
2      0.87
3      1.11
4       0.7
5      0.54
6     -0.09
7     -0.05
8     -0.85
9     -1.72
10    -0.62
11    -2.07
12    -1.52
13     0.16
14    -0.54
15      0.8
16    -0.79
17    -1.89
18    -0.32
19      0.5
20     0.58
21    -0.33
22     0.05
23    -0.21
24    -1.08
25     0.39
26    -1.12
27    -0.46
28    -1.06
29     0.29
30    -0.02
31     1.24
32    -0.18
33    -0.29
34     -0.5
35     0.06
36    -0.87
37    -0.45
38    -0.94
39     0.57
40    -0.21
41    -1.95
42    -1.38
43     1.05
44     0.82
45     0.35
46     0.92
47    -0.62
48      1.3
49     0.53
dtype: object>

In [14]:
a.clip_upper(.28).head() #threshold upper most limit

AttributeError: 'Series' object has no attribute 'clip_Upper'

In [15]:
a.clip_lower(.33).head()

AttributeError: 'Series' object has no attribute 'clip_lower'

# Replacing value

In [ ]:
clths= pd.Series([])

# Assignement question


In [ ]:
#Write a Python program for sum of any 3 elements is 8 from a given list and display output as below. list = [1,2,3,4,5,6,7]
#Output: 1+3+4 = 8 , 1+2+5 = 8

In [5]:
li =[1,2,3,4,5,6,7]
print(li[0])

def add():
    if((li[0]+li[1]+li[2])==8):
        print(li[0]+str(+)+li[1]+str(+)+li[2]"=8")
    elif((li[0]+li[2]+li[3])==8):
          print(li[0]+str(+)+li[1]+str(+)+li[2]"=8")
add()

1


In [6]:
def add():
    if((li[0]+li[1]+li[2])==8):
        print(li[0])
    elif((li[0]+li[2]+li[3])==8):
          print(li[0]+li[1]+li[2])
add()

6


In [60]:
#Write a program to SWAP the first and last value of a list

def listchange(li):
     
    li[0], li[-1] = li[-1], li[0]
 
    return li

li=[23,13,14,56]
print(li)
print(listchange(newList))

[23, 13, 14, 56]
[56, 13, 14, 23]


In [89]:
#Write a Python program to reverse a number in Python.
list=(1,2,3)
print(list)

print(list[::-1])



(1, 2, 3)
(3, 2, 1)


In [100]:
#10.Write a Python program to check if a number is a Strong Number.
n=0
a= int(input())
temp=a
while(a):
    i=1
    fac=1
    r=a%10
    while(i<=r):
        fac=fac*i
        i=i+1
    n=n+fac
    a=a//10
        
if(n==temp):
    print("The number is a strong number")
else:
    print("The number is not a strong number")
        

145
The number is a strong number


# dataframes

In [8]:
import numpy as np

In [9]:
import pandas as pd

In [3]:
x=[1,2,3,5]
d1=pd.DataFrame(x)
d1

0
0  1
1  2
2  3
3  5

In [4]:
data=[['abc',12,""],["efg",23,""],["hij",12,""]]
d2=pd.DataFrame(data)
d2

0   1 2
0  abc  12  
1  efg  23  
2  hij  12

# creating df from dict

In [5]:
data= {"name":["abc","def","ghi"],"age":[12,13,33]}
x= pd.DataFrame(data)
x

name  age
0  abc   12
1  def   13
2  ghi   33

# create a df from list of dics

In [6]:
data=[{"a":3,"b":4},{"a":43,"b":"xyz","c":33}]
x=pd.DataFrame(data)
x

a    b     c
0   3    4   NaN
1  43  xyz  33.0

## using a dic of equal length lists

In [5]:
x={"ints":np.arange(5),"floats":np.arange(0.1,6.0,1.4),"strings":list("abcde")}
x

{'ints': array([0, 1, 2, 3, 4]),
 'floats': array([0.1, 1.5, 2.9, 4.3, 5.7]),
 'strings': ['a', 'b', 'c', 'd', 'e']}

In [6]:
df4=pd.DataFrame(x,index=list("abcde"))
df4

ints  floats strings
a     0     0.1       a
b     1     1.5       b
c     2     2.9       c
d     3     4.3       d
e     4     5.7       e

In [11]:
df4.dtypes

ints         int32
floats     float64
strings     object
dtype: object

# subsetting 

# selecting a single row/columns

In [7]:
import numpy as np
df5= pd.DataFrame(np.arange(10,30),

NameError: name 'reshape' is not defined

In [11]:
df4["floats"]

a    0.1
b    1.5
c    2.9
d    4.3
e    5.7
Name: floats, dtype: float64

In [12]:
df4.iloc[1]

ints         1
floats     1.5
strings      b
Name: b, dtype: object

# Practice csv

In [2]:
url="phone_data.csv"
df=pd.read_csv(url)
df.head()

NameError: name 'pd' is not defined

In [77]:
d3=df[df.item=="call"]
print(d3)

     index            date  duration  item    month   network network_type
1        1  15/10/14 06:58      13.0  call  2014-11  Vodafone       mobile
2        2  15/10/14 14:46      23.0  call  2014-11    Meteor       mobile
3        3  15/10/14 14:48       4.0  call  2014-11     Tesco       mobile
4        4  15/10/14 17:27       4.0  call  2014-11     Tesco       mobile
5        5  15/10/14 18:55       4.0  call  2014-11     Tesco       mobile
..     ...             ...       ...   ...      ...       ...          ...
807    807  03/03/15 10:12     745.0  call  2015-03  Vodafone       mobile
808    808  03/03/15 10:27      57.0  call  2015-03  Vodafone       mobile
809    809  03/03/15 14:34    1325.0  call  2015-03  Vodafone       mobile
810    810  03/03/15 18:36     768.0  call  2015-03     Three       mobile
816    816  04/03/15 12:29   10528.0  call  2015-03  landline     landline

[388 rows x 7 columns]


In [78]:
d3["duration"].max()   #q1

10528.0

In [79]:
df.dtypes

index             int64
date             object
duration        float64
item             object
month            object
network          object
network_type     object
dtype: object

In [80]:
d3[d3["duration"]==10528.0]

index            date  duration  item    month   network network_type
816    816  04/03/15 12:29   10528.0  call  2015-03  landline     landline

In [81]:
d3["duration"].sum() #How many seconds of phone calls are recorded in total?

92321.0

In [82]:
d6=df.groupby("month").item.count()
print(d6)
#How many entries are there for each month?

month
2014-11    230
2014-12    157
2015-01    205
2015-02    137
2015-03    101
Name: item, dtype: int64


In [83]:
#Number of non-null unique network entries

d4=pd.notnull(df["network"])
print(d4)

0      True
1      True
2      True
3      True
4      True
       ... 
825    True
826    True
827    True
828    True
829    True
Name: network, Length: 830, dtype: bool


In [84]:
d4.count()

830

In [85]:
df.isnull().sum()

index           0
date            0
duration        0
item            0
month           0
network         0
network_type    0
dtype: int64

In [86]:
#Get the first entry for each month
print(d6)


month
2014-11    230
2014-12    157
2015-01    205
2015-02    137
2015-03    101
Name: item, dtype: int64


In [87]:
#Get the sum of the durations per month

d7=df.groupby("month").sum()
print(d7)

          index   duration
month                     
2014-11   26337  26639.441
2014-12   48362  14641.870
2015-01  100259  18223.299
2015-02   90398  15522.299
2015-03   78679  22750.441


In [ ]:
#Get the number of dates / entries in each month



In [104]:
#What is the sum of durations, for calls only, to each network
#d3=df[df.item=="call"]


d8= d3.groupby("network").duration.sum()
d8

network
Meteor        7200.0
Tesco        13828.0
Three        36464.0
Vodafone     14621.0
landline     18433.0
voicemail     1775.0
Name: duration, dtype: float64

In [103]:
# How many calls, sms, and data entries are in each month?
d9= df.groupby(["month","item","network"]).index.count().unstack() 
print(d9)

network       Meteor  Tesco  Three  Vodafone  data  landline  special  \
month   item                                                            
2014-11 call    13.0   20.0   39.0      24.0   NaN       5.0      NaN   
        data     NaN    NaN    NaN       NaN  29.0       NaN      NaN   
        sms     10.0    3.0   25.0      55.0   NaN       NaN      1.0   
2014-12 call    12.0   12.0   30.0      10.0   NaN       7.0      NaN   
        data     NaN    NaN    NaN       NaN  30.0       NaN      NaN   
        sms     12.0    1.0   13.0      18.0   NaN       NaN      NaN   
2015-01 call    21.0   12.0   26.0      15.0   NaN      11.0      NaN   
        data     NaN    NaN    NaN       NaN  31.0       NaN      NaN   
        sms     10.0    3.0   33.0      40.0   NaN       NaN      NaN   
2015-02 call     4.0   20.0   22.0       7.0   NaN       8.0      NaN   
        data     NaN    NaN    NaN       NaN  31.0       NaN      NaN   
        sms      1.0    2.0   11.0      23.0   NaN 

In [92]:
#Group the dataframe by month and item and extract a number of stats from each group
    
d11= df.groupby("month","item")

In [ ]:
#Define the aggregation procedure outside of the groupby operation

d10= df.groupby("month").item.agg[('count',"min","max","mean")]